<div style="text-align: center;">
  <img src="./imagens/logo_novaims.png" alt="Logo" style="width: 150px; height: auto; margin-bottom: 10px;">
  <h1 style="margin: 0;"><strong>Machine Learning Project: Amazing International Airlines Inc.</strong></h1>
  <h2 style="margin: 0;"><strong>Part 1/2: Exploratory Data Analysis</strong></h2>
</div>

<div style="text-align: left; margin-top: 15px;">
  <p style="margin: 0;"><strong>Group 51:</strong></p>
  <ul style="margin: 0; padding-left: 20px;">
    <li>André Ferreira | 20250398</li>
    <li>Fausto Gomes | 20221915</li>
    <li>Maria Francisca Gonçalves | 20221942</li>
    <li>Miguel Matos | 20221925</li>
  </ul>
</div>

---
#### <font> Table of Contents </font> <a class="anchor" id='toc'></a> 
0. [Context](#introduction)
1. [Imports](#Imports)  
2. [Exploratory Data Analysis - Customer Data](#exploratory-data-analysis)

- 2.1. [Data Understanding](#21-data-understanding)
  - 2.1.1.[Descriptive Analysis](#descriptive-analysis)
  - 2.1.2.[Visualizations](#visualizations)

- 2.2. [GeoData](#geodata)

- 2.3. [Data Cleaning](#data-cleaning)



----

# <span style="color:#0097b2">0. Context</span>
[Back to TOC](#toc)

# <span style="color:#0097b2">1. Imports</span>
[Back to TOC](#toc)

In [8]:
import warnings
import pandas as pd
import numpy as np

# Suppress this specific warning
warnings.filterwarnings('ignore', 
                       message='X does not have valid feature names',
                       category=UserWarning,
                       module='sklearn.utils.validation')


customer_data = pd.read_csv("../data/cleaned_data/customers_data_cleaned.csv", index_col= 0)
flights_data = pd.read_csv("../data/cleaned_data/flights_data_cleaned.csv", index_col= 0)

pd.set_option("display.max_columns", None)

In [2]:
data = pd.merge(
    customer_data, 
    flights_data, 
    on='Loyalty#', 
    how='outer' # To keep all clients registered
)

# The merge might create NaNs for customers in df_clean who had zero flight history
# For clustering, we should fill these with 0
features_to_fill = [
    'TotalFlights', 
    'TotalDistance', 
    'TotalPointsAccumulated', 
    'TotalPointsRedeemed'
]
data[features_to_fill] = data[features_to_fill].fillna(0)

# If 'RecencyInMonths' is NaN (from the 'left' merge), it means they never flew. 
# We can keep the 999 we set earlier, or set it again.
data['RecencyInMonths'] = data['RecencyInMonths'].fillna(999)

In [3]:
flights_data

,Loyalty#,TotalFlights,TotalDistance,TotalPointsAccumulated,TotalPointsRedeemed,LastFlightDate,RecencyInMonths,Pct_Spend_Month_1,Pct_Spend_Month_2,Pct_Spend_Month_3,Pct_Spend_Month_4,Pct_Spend_Month_5,Pct_Spend_Month_6,Pct_Spend_Month_7,Pct_Spend_Month_8,Pct_Spend_Month_9,Pct_Spend_Month_10,Pct_Spend_Month_11,Pct_Spend_Month_12,Flights_per_day
0,100018,229.9,530230.0,53014.30,20562.8,2021-12-01,1.018397,0.048421,0.060858,0.074292,0.061981,0.000000,0.132689,0.137946,0.108319,0.073489,0.065397,0.124303,0.112304,0.209954
1,100102,247.7,339114.6,33903.96,18760.6,2021-12-01,1.018397,0.060884,0.028640,0.033403,0.049635,0.046809,0.080404,0.114205,0.014635,0.179591,0.152183,0.057872,0.181741,0.226210
2,100140,216.8,432030.8,43192.58,4896.0,2021-11-01,2.003942,0.043443,0.000000,0.172908,0.012598,0.164527,0.065297,0.164342,0.008060,0.079373,0.009099,0.135146,0.145208,0.197991
3,100214,112.3,364601.7,36453.77,12908.6,2021-12-01,1.018397,0.000000,0.065188,0.057415,0.000000,0.000000,0.169642,0.000000,0.224220,0.135728,0.089849,0.007416,0.250542,0.102557
4,100272,186.4,429630.5,42953.25,10891.4,2021-11-01,2.003942,0.034945,0.110526,0.078136,0.041127,0.054967,0.167454,0.070783,0.179004,0.024562,0.044607,0.051625,0.142265,0.170228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16732,999902,267.1,610159.5,61006.55,10501.8,2021-10-01,3.022339,0.099376,0.089763,0.087597,0.051506,0.073032,0.148470,0.099877,0.122778,0.007860,0.081661,0.031620,0.106458,0.243927
16733,999911,0.0,0.0,0.00,0.0,NaN,999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16734,999940,85.5,238578.9,23855.59,5620.0,2021-12-01,1.018397,0.000000,0.000000,0.114145,0.000000,0.000000,0.000000,0.000000,0.121733,0.254003,0.000000,0.308023,0.202095,0.078082
16735,999982,22.0,52654.0,5264.00,0.0,2021-11-01,2.003942,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017857,0.524696,0.000000,0.240502,0.216945,0.020091
16736,999986,185.8,345117.6,34506.96,18049.4,2021-11-01,2.003942,0.090529,0.172165,0.221945,0.065589,0.028265,0.000000,0.028748,0.133057,0.112986,0.116810,0.029907,0.000000,0.169680

In [4]:
data.head(10)

,Loyalty#,First Name,Last Name,Customer Name,Country,Province or State,City,Latitude,Longitude,Postal code,Gender,Education,Location Code,Income,Marital Status,LoyaltyStatus,EnrollmentDateOpening,CancellationDate,Customer Lifetime Value,EnrollmentType,rejoined_program,Days_in_prog,Cancelled_program,Enrollment_year,Enrollment_month,Location_cluster,TotalFlights,TotalDistance,TotalPointsAccumulated,TotalPointsRedeemed,LastFlightDate,RecencyInMonths,Pct_Spend_Month_1,Pct_Spend_Month_2,Pct_Spend_Month_3,Pct_Spend_Month_4,Pct_Spend_Month_5,Pct_Spend_Month_6,Pct_Spend_Month_7,Pct_Spend_Month_8,Pct_Spend_Month_9,Pct_Spend_Month_10,Pct_Spend_Month_11,Pct_Spend_Month_12,Flights_per_day
0,100011,Amelia,Ross,Amelia Ross,Canada,Ontario,Toronto,43.593187,-79.444335,W9D 4Q9,female,Bachelor,Suburban,NaN,Married,Star,2017-05-01,2017-05-01,NaN,Standard,0,0.0,0,2017,5,1,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100012,Ethan,Thompson,Ethan Thompson,Canada,Quebec,Quebec City,46.759733,-71.141009,Y0C 7D6,male,Bachelor,Suburban,NaN,Single,Star,2019-02-27,2019-02-27,NaN,Standard,0,0.0,0,2019,2,4,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100013,Layla,Young,Layla Young,Canada,Alberta,Edmonton,53.524829,-113.546357,L3S 9Y3,female,Bachelor,Rural,NaN,Married,Star,2017-09-20,2017-09-20,NaN,Standard,0,0.0,0,2017,9,5,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100014,Amelia,Bennett,Amelia Bennett,Canada,New Brunswick,Moncton,46.051866,-64.825428,G2S 2B6,male,Bachelor,Rural,NaN,Married,Star,2020-11-28,2020-11-28,NaN,Standard,0,0.0,0,2020,11,3,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100015,Benjamin,Wilson,Benjamin Wilson,Canada,Quebec,Quebec City,46.862970,-71.133444,B1Z 8T3,female,College,Urban,NaN,Married,Star,2020-04-09,2020-04-09,NaN,Standard,0,0.0,0,2020,4,4,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,100016,Emma,Martin,Emma Martin,Canada,British Columbia,Dawson Creek,55.720562,-120.160090,M4A 1E4,female,Master,Suburban,NaN,Single,Star,2020-07-21,2020-07-21,NaN,Standard,0,0.0,0,2020,7,5,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,100017,Grace,Fortin,Grace Fortin,Canada,British Columbia,Dawson Creek,55.751178,-120.264920,E0K 5I2,male,Master,Urban,NaN,Married,Star,2017-04-11,2017-04-11,NaN,Standard,0,0.0,0,2017,4,5,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,100018,Mina,Smida,Mina Smida,Canada,Alberta,Edmonton,53.544388,-113.490930,T9G 1W3,female,Bachelor,Rural,82877.0,Married,Aurora,2019-08-09,NaN,7919.20,Standard,0,874.0,0,2019,8,5,229.9,530230.0,53014.30,20562.8,2021-12-01,1.018397,0.048421,0.060858,0.074292,0.061981,0.000000,0.132689,0.137946,0.108319,0.073489,0.065397,0.124303,0.112304,0.209954
8,100102,Rigoberto,Palacio,Rigoberto Palacio,Canada,Ontario,Toronto,43.653225,-79.383186,M1R 4K3,male,College,Urban,0.0,Single,Nova,2016-03-09,NaN,2887.74,Standard,0,2122.0,0,2016,3,1,247.7,339114.6,33903.96,18760.6,2021-12-01,1.018397,0.060884,0.028640,0.033403,0.049635,0.046809,0.080404,0.114205,0.014635,0.179591,0.152183,0.057872,0.181741,0.226210
9,100140,Nakesha,Klaass,Nakesha Klaass,Canada,British Columbia,Dawson Creek,55.759628,-120.237660,U5I 4F1,female,College,Suburban,0.0,Divorced,Nova,2019-07-30,NaN,2838.07,Standard,0,884.0,0,2019,7,5,216.8,432030.8,43192.58,4896.0,2021-11-01,2.003942,0.043443,0.000000,0.172908,0.012598,0.164527,0.065297,0.164342,0.008060,0.079373,0.009099,0.135146,0.145208,0.197991

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16757 entries, 0 to 16756
Data columns (total 45 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Loyalty#                 16757 non-null  int64
 1   First Name               16757 non-null  object
 2   Last Name                16757 non-null  object
 3   Customer Name            16757 non-null  object
 4   Country                  16757 non-null  object
 5   Province or State        16757 non-null  object
 6   City                     16757 non-null  object
 7   Latitude                 16757 non-null  float64
 8   Longitude                16757 non-null  float64
 9   Postal code              16757 non-null  object
 10  Gender                   16757 non-null  object
 11  Education                16757 non-null  object
 12  Location Code            16757 non-null  object
 13  Income                   16737 non-null  float64
 14  Marital Status           16757 non-null  object
 15  LoyaltyStatus            16757 non-null  object
 16  EnrollmentDateOpening    16757 non-null  object
 17  CancellationDate         2286 non-null   object
 18  Customer Lifetime Value  16737 non-null  float64
 19  EnrollmentType           16757 non-null  object
 20  rejoined_program         16757 non-null  int64
 21  Days_in_prog             16757 non-null  float64
 22  Cancelled_program        16757 non-null  int64
 23  Enrollment_year          16757 non-null  int64
 24  Enrollment_month         16757 non-null  int64
 25  Location_cluster         16757 non-null  int64
 26  TotalFlights             16757 non-null  float64
 27  TotalDistance            16757 non-null  float64
 28  TotalPointsAccumulated   16757 non-null  float64
 29  TotalPointsRedeemed      16757 non-null  float64
 30  LastFlightDate           15236 non-null  object
 31  RecencyInMonths          16757 non-null  float64
 32  Pct_Spend_Month_1        16737 non-null  float64
 33  Pct_Spend_Month_2        16737 non-null  float64
 34  Pct_Spend_Month_3        16737 non-null  float64
 35  Pct_Spend_Month_4        16737 non-null  float64
 36  Pct_Spend_Month_5        16737 non-null  float64
 37  Pct_Spend_Month_6        16737 non-null  float64
 38  Pct_Spend_Month_7        16737 non-null  float64
 39  Pct_Spend_Month_8        16737 non-null  float64
 40  Pct_Spend_Month_9        16737 non-null  float64
 41  Pct_Spend_Month_10       16737 non-null  float64
 42  Pct_Spend_Month_11       16737 non-null  float64
 43  Pct_Spend_Month_12       16737 non-null  float64
 44  Flights_per_day          16737 non-null  float64
dtypes: float64(23), int64(6), object(16)
memory usage: 5.8+ MB

### Feature Engeneering

In [9]:
data["Avg_spent_per_flight"] = np.where(data["EnrollmentDateOpening"] >= "2019-01-01",
                                        data["Customer Lifetime Value"]/(data["Flights_per_day"] * data["Days_in_prog"]),
                                        np.nan)

"Inf" means infinity, which happens when the divisor is zero, so when "Days_in_prog" or "Flights_per_day" is zero. To handle this, we will feel it with Nan for now.

In [10]:
data["Avg_spent_per_flight"] = data["Avg_spent_per_flight"].replace(np.inf, np.nan)

In [11]:
data["Avg_spent_per_flight"].describe()

count      7491.000000
mean       1960.837518
std       12811.625099
min           6.359410
25%          51.737521
50%         147.920551
75%         571.234834
max      749883.717188
Name: Avg_spent_per_flight, dtype: float64

In [12]:
data.head(10)

,Loyalty#,First Name,Last Name,Customer Name,Country,Province or State,City,Latitude,Longitude,Postal code,Gender,Education,Location Code,Income,Marital Status,LoyaltyStatus,EnrollmentDateOpening,CancellationDate,Customer Lifetime Value,EnrollmentType,rejoined_program,Days_in_prog,Cancelled_program,Enrollment_year,Enrollment_month,Location_cluster,TotalFlights,TotalDistance,TotalPointsAccumulated,TotalPointsRedeemed,LastFlightDate,RecencyInMonths,Pct_Spend_Month_1,Pct_Spend_Month_2,Pct_Spend_Month_3,Pct_Spend_Month_4,Pct_Spend_Month_5,Pct_Spend_Month_6,Pct_Spend_Month_7,Pct_Spend_Month_8,Pct_Spend_Month_9,Pct_Spend_Month_10,Pct_Spend_Month_11,Pct_Spend_Month_12,Flights_per_day,Avg_spent_per_flight
0,100011,Amelia,Ross,Amelia Ross,Canada,Ontario,Toronto,43.593187,-79.444335,W9D 4Q9,female,Bachelor,Suburban,NaN,Married,Star,2017-05-01,2017-05-01,NaN,Standard,0,0.0,0,2017,5,1,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100012,Ethan,Thompson,Ethan Thompson,Canada,Quebec,Quebec City,46.759733,-71.141009,Y0C 7D6,male,Bachelor,Suburban,NaN,Single,Star,2019-02-27,2019-02-27,NaN,Standard,0,0.0,0,2019,2,4,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100013,Layla,Young,Layla Young,Canada,Alberta,Edmonton,53.524829,-113.546357,L3S 9Y3,female,Bachelor,Rural,NaN,Married,Star,2017-09-20,2017-09-20,NaN,Standard,0,0.0,0,2017,9,5,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100014,Amelia,Bennett,Amelia Bennett,Canada,New Brunswick,Moncton,46.051866,-64.825428,G2S 2B6,male,Bachelor,Rural,NaN,Married,Star,2020-11-28,2020-11-28,NaN,Standard,0,0.0,0,2020,11,3,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100015,Benjamin,Wilson,Benjamin Wilson,Canada,Quebec,Quebec City,46.862970,-71.133444,B1Z 8T3,female,College,Urban,NaN,Married,Star,2020-04-09,2020-04-09,NaN,Standard,0,0.0,0,2020,4,4,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,100016,Emma,Martin,Emma Martin,Canada,British Columbia,Dawson Creek,55.720562,-120.160090,M4A 1E4,female,Master,Suburban,NaN,Single,Star,2020-07-21,2020-07-21,NaN,Standard,0,0.0,0,2020,7,5,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,100017,Grace,Fortin,Grace Fortin,Canada,British Columbia,Dawson Creek,55.751178,-120.264920,E0K 5I2,male,Master,Urban,NaN,Married,Star,2017-04-11,2017-04-11,NaN,Standard,0,0.0,0,2017,4,5,0.0,0.0,0.00,0.0,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,100018,Mina,Smida,Mina Smida,Canada,Alberta,Edmonton,53.544388,-113.490930,T9G 1W3,female,Bachelor,Rural,82877.0,Married,Aurora,2019-08-09,NaN,7919.20,Standard,0,874.0,0,2019,8,5,229.9,530230.0,53014.30,20562.8,2021-12-01,1.018397,0.048421,0.060858,0.074292,0.061981,0.000000,0.132689,0.137946,0.108319,0.073489,0.065397,0.124303,0.112304,0.209954,43.156382
8,100102,Rigoberto,Palacio,Rigoberto Palacio,Canada,Ontario,Toronto,43.653225,-79.383186,M1R 4K3,male,College,Urban,0.0,Single,Nova,2016-03-09,NaN,2887.74,Standard,0,2122.0,0,2016,3,1,247.7,339114.6,33903.96,18760.6,2021-12-01,1.018397,0.060884,0.028640,0.033403,0.049635,0.046809,0.080404,0.114205,0.014635,0.179591,0.152183,0.057872,0.181741,0.226210,NaN
9,100140,Nakesha,Klaass,Nakesha Klaass,Canada,British Columbia,Dawson Creek,55.759628,-120.237660,U5I 4F1,female,College,Suburban,0.0,Divorced,Nova,2019-07-30,NaN,2838.07,Standard,0,884.0,0,2019,7,5,216.8,432030.8,43192.58,4896.0,2021-11-01,2.003942,0.043443,0.000000,0.172908,0.012598,0.164527,0.065297,0.164342,0.008060,0.079373,0.009099,0.135146,0.145208,0.197991,16.215326

In [13]:
clustering_data = data.drop(columns= ["First Name", "Last Name", "Customer Name", "Country", "Province or State", "City", 
                            "Latitude", "Longitude", "Postal code", "Loyalty#", "Gender", "Education", "Location Code", 
                            "Marital Status", "LoyaltyStatus", "EnrollmentDateOpening", "CancellationDate", 
                            "EnrollmentType", "rejoined_program", "Cancelled_program", "LastFlightDate",  "Avg_spent_per_flight"])

In [14]:
clustering_data.head(10)

,Income,Customer Lifetime Value,Days_in_prog,Enrollment_year,Enrollment_month,Location_cluster,TotalFlights,TotalDistance,TotalPointsAccumulated,TotalPointsRedeemed,RecencyInMonths,Pct_Spend_Month_1,Pct_Spend_Month_2,Pct_Spend_Month_3,Pct_Spend_Month_4,Pct_Spend_Month_5,Pct_Spend_Month_6,Pct_Spend_Month_7,Pct_Spend_Month_8,Pct_Spend_Month_9,Pct_Spend_Month_10,Pct_Spend_Month_11,Pct_Spend_Month_12,Flights_per_day
0,NaN,NaN,0.0,2017,5,1,0.0,0.0,0.00,0.0,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0.0,2019,2,4,0.0,0.0,0.00,0.0,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,0.0,2017,9,5,0.0,0.0,0.00,0.0,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,0.0,2020,11,3,0.0,0.0,0.00,0.0,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,0.0,2020,4,4,0.0,0.0,0.00,0.0,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,0.0,2020,7,5,0.0,0.0,0.00,0.0,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,0.0,2017,4,5,0.0,0.0,0.00,0.0,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,82877.0,7919.20,874.0,2019,8,5,229.9,530230.0,53014.30,20562.8,1.018397,0.048421,0.060858,0.074292,0.061981,0.000000,0.132689,0.137946,0.108319,0.073489,0.065397,0.124303,0.112304,0.209954
8,0.0,2887.74,2122.0,2016,3,1,247.7,339114.6,33903.96,18760.6,1.018397,0.060884,0.028640,0.033403,0.049635,0.046809,0.080404,0.114205,0.014635,0.179591,0.152183,0.057872,0.181741,0.226210
9,0.0,2838.07,884.0,2019,7,5,216.8,432030.8,43192.58,4896.0,2.003942,0.043443,0.000000,0.172908,0.012598,0.164527,0.065297,0.164342,0.008060,0.079373,0.009099,0.135146,0.145208,0.197991

# Preprocessing

As most for most columns they only contain 20 missing values, we'll just fill them with the median.

In [15]:
clustering_data.isna().sum()

Income                     20
Customer Lifetime Value    20
Days_in_prog                0
Enrollment_year             0
Enrollment_month            0
Location_cluster            0
TotalFlights                0
TotalDistance               0
TotalPointsAccumulated      0
TotalPointsRedeemed         0
RecencyInMonths             0
Pct_Spend_Month_1          20
Pct_Spend_Month_2          20
Pct_Spend_Month_3          20
Pct_Spend_Month_4          20
Pct_Spend_Month_5          20
Pct_Spend_Month_6          20
Pct_Spend_Month_7          20
Pct_Spend_Month_8          20
Pct_Spend_Month_9          20
Pct_Spend_Month_10         20
Pct_Spend_Month_11         20
Pct_Spend_Month_12         20
Flights_per_day            20
dtype: int64

In [16]:
#Imputing each column missing values with their median
clustering_data = clustering_data.fillna(clustering_data.median())

In [17]:
clustering_data.isna().sum()

Income                     0
Customer Lifetime Value    0
Days_in_prog               0
Enrollment_year            0
Enrollment_month           0
Location_cluster           0
TotalFlights               0
TotalDistance              0
TotalPointsAccumulated     0
TotalPointsRedeemed        0
RecencyInMonths            0
Pct_Spend_Month_1          0
Pct_Spend_Month_2          0
Pct_Spend_Month_3          0
Pct_Spend_Month_4          0
Pct_Spend_Month_5          0
Pct_Spend_Month_6          0
Pct_Spend_Month_7          0
Pct_Spend_Month_8          0
Pct_Spend_Month_9          0
Pct_Spend_Month_10         0
Pct_Spend_Month_11         0
Pct_Spend_Month_12         0
Flights_per_day            0
dtype: int64

In [20]:
clustering_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16757 entries, 0 to 16756
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Income                   16757 non-null  float64
 1   Customer Lifetime Value  16757 non-null  float64
 2   Days_in_prog             16757 non-null  float64
 3   Enrollment_year          16757 non-null  int64
 4   Enrollment_month         16757 non-null  int64
 5   Location_cluster         16757 non-null  int64
 6   TotalFlights             16757 non-null  float64
 7   TotalDistance            16757 non-null  float64
 8   TotalPointsAccumulated   16757 non-null  float64
 9   TotalPointsRedeemed      16757 non-null  float64
 10  RecencyInMonths          16757 non-null  float64
 11  Pct_Spend_Month_1        16757 non-null  float64
 12  Pct_Spend_Month_2        16757 non-null  float64
 13  Pct_Spend_Month_3        16757 non-null  float64
 14  Pct_Spend_Month_4        16757 non-null  float64
 15  Pct_Spend_Month_5        16757 non-null  float64
 16  Pct_Spend_Month_6        16757 non-null  float64
 17  Pct_Spend_Month_7        16757 non-null  float64
 18  Pct_Spend_Month_8        16757 non-null  float64
 19  Pct_Spend_Month_9        16757 non-null  float64
 20  Pct_Spend_Month_10       16757 non-null  float64
 21  Pct_Spend_Month_11       16757 non-null  float64
 22  Pct_Spend_Month_12       16757 non-null  float64
 23  Flights_per_day          16757 non-null  float64
dtypes: float64(21), int64(3)
memory usage: 3.1 MB

# Outlier Analysis

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors
from kneed import KneeLocator
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Assuming you have a DataFrame named 'people' with purchase data

# Selecting relevant features for clustering
X = people_sem_pescadores[['percentage_of_products_bought_promotion', 
            'number_complaints', 'percentage_spend_vegetables', 'percentage_spend_nonalcohol_drinks', 
            'percentage_spend_alcohol_drinks', 'percentage_spend_meat', 'percentage_spend_fish', 
            'percentage_spend_hygiene', 'percentage_spend_videogames', 'percentage_spend_petfood', 'percentage_spend_groceries', 
            'percentage_spend_electronics', 'teens_home', 'kids_home']]

# Standardizing the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Calculating the distance to the k-nearest neighbor
nearest_neighbors = NearestNeighbors(n_neighbors=5)
nearest_neighbors.fit(X_scaled)
distances, _ = nearest_neighbors.kneighbors(X_scaled)

# Sorting the distances and plotting the knee point
distances = np.sort(distances, axis=0)
distances = distances[:,1]  # consider the second nearest neighbor (the first one is itself)
plt.plot(distances)
plt.title("Elbow Curve for DBSCAN")
plt.xlabel("Data Point Index")
plt.ylabel("Epsilon")
plt.show()

# Finding the knee point to determine epsilon
kneedle = KneeLocator(range(len(distances)), distances, curve='convex', direction='increasing')
epsilon = distances[kneedle.knee]
print(f"Optimal epsilon: {epsilon}")

# Applying DBSCAN with the optimal epsilon
dbscan = DBSCAN(eps=epsilon, min_samples=5)
clusters = dbscan.fit_predict(X_scaled)

# Extracting outliers
outliers_mask = clusters == -1
outliers = X[outliers_mask]

print("Number of outliers:", len(outliers))

# You can further analyze the outliers as needed
print(outliers.head())

# Visualizing the clusters
plt.figure(figsize=(10, 6))

# Plotting points
plt.scatter(X_scaled[:, 0], X_scaled[:, 1], c=clusters, cmap='viridis', s=50, alpha=0.5)
plt.scatter(X_scaled[outliers_mask, 0], X_scaled[outliers_mask, 1], c='red', marker='x', label='Outliers')
plt.xlabel('Scaled Feature 1')
plt.ylabel('Scaled Feature 2')
plt.title('DBSCAN Clustering with Outliers')

plt.legend()
plt.show()

KeyboardInterrupt: